# Generated by Django 4.2.2 on 2023-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phonenumber', models.CharField(max_length=32)),
            ],
        ),
    ]
